name: Build documentation
on:
  workflow_dispatch: {}
env:
  TRL_EXPERIMENTAL_SILENCE: 1
jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@main
    with:
      commit_sha: ${{ github.sha }}
      package: trl
      version_tag_suffix: ''
    secrets:
      hf_token: ${{ secrets.HF_DOC_BUILD_PUSH }}
